"""Extend audit logs with resource metadata

Revision ID: de84c8dad023
Revises: ab21ceea979f
Create Date: 2026-08-23 13:36:37.220969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de84c8dad023'
down_revision: Union[str, Sequence[str], None] = 'ab21ceea979f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('resource_type', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('resource_id', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('result', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'result')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'resource_type')
    # ### end Alembic commands ###
